### ISSUE TITLE
Updates for OJS 3.2+ compatibility

### ISSUE THREAD

**Issue by mfelczak** [mfelczak/bepress#11]
Article versioning was introduced in OJS 3.2 with corresponding data object updates.

See https://docs.pkp.sfu.ca/dev/release-notebooks/en/3.2-release-notebook

**Comment by ewhanson** [comment]
Hi, @mfelczak. I've updated the plugin to work with the new versioning system (submissions and publications). It imported the test issue and the sample metadata successfully.

Let me know if any other changes are needed.

Pull request:
#12

**Comment by mfelczak** [comment]
Merged, thanks @ewhanson!
