### ISSUE TITLE
Import title, keywords, subject areas in multiple locales for OJS 3.2+

### ISSUE THREAD

**Issue by mfelczak** [mfelczak/bepress#13]
Add support for "locale" attribute in title, keyword, and subject-area tags to allow import of multi-lingual metadata, e.g. <title locale="en_US">Full article title</title>

Use existing OJS locale abbreviations as valid attribute values, e.g. "en_US", "de_DE", see https://github.com/pkp/ojs/tree/stable-3_2_0/locale

If "locale" attribute is not specified, import text using the journal's primary locale (current default).

The following examples would be considered valid:

`<title>Full article title</title>`

`<title locale="en_US">Full article title</title>`

```
<keywords>
<keyword locale="en_US">Keyword</keyword>
<keyword locale="fr_CA">Mot-clé</keyword>
</keywords>
```

**Comment by ewhanson** [comment]
Hi @mfelczak,

I've created a pull request that updates our ability to import localized fields. It encompasses titles, abstracts (which was already present), keywords, subject areas, and disciplines. Let me know if you have any questions.

PR:
#14

Thanks!

**Comment by mfelczak** [comment]
Hi @ewhanson,

Thanks! That looks great, and the new localized helper method is a nice addition. Just a few stray comments which I've noted in the PR. Once you're able to remove them, I'll merge this in.

**Comment by ewhanson** [comment]
Thanks, @mfelczak! I've removed the comments you noted.

**Comment by mfelczak** [comment]
Merged, closing.
