### ISSUE TITLE
Import localized author first, middle, last names, institution for OJS 3.2+

### ISSUE THREAD

**Issue by ewhanson** [mfelczak/bepress#15]
Add support for "locale" attribute in `institution`, `fname`, `mname`, and `lname` to allow import of multi-lingual metadata.

If "locale" attribute is not specified, import text using the journal's primary locale (current default).

**Comment by ewhanson** [comment]
Both of the following would be considered valid constructions of `lname`:

```XML
<!-- With multiple locales -->
<author>
    ...
    <lnames>
        <lname locale="en_US">Lastname</lname>
        <lname locale="de_DE">Nachname</lname>
    </lnames>
    ...
</author>

<!-- With unspecified locale -->
<author>
    ...
    <lname>Lastname</lname>
    ...
</author>
```

**Comment by ewhanson** [comment]
Hi @mfelczak,

Here are the localization additions for the bepress import plugin. I've added support support for `fname`, `mname`, `lname`, `suffix`, and `institution`.

PR:
#16 

Let me know if it needs any changes.

Thanks!

**Comment by mfelczak** [comment]
Merged, closing.
