### ISSUE TITLE
Provide single and multiple locale sample metadata XML

### ISSUE THREAD

**Issue by mfelczak** [mfelczak/bepress#17]
At the moment we have an updated sample-metadata.xml that provides a multi-locale example of valid import data. Let's rename this to sample-metadata-multiple-locales.xml and create a new sample file for single locale import, sample-metadata-single-locale.xml to illustrate the difference between both import modes.

**Comment by mfelczak** [comment]
Hi @ewhanson, just a note to let you know that I've assigned you to this issue.

**Comment by ewhanson** [comment]
Thanks @mfelczak . I'll get these added.

**Comment by ewhanson** [comment]
Hi @mfelczak, added examples for each and some links to them in the readme.

PR: 
#18 

Let me know if there are any other changes needed.

**Comment by mfelczak** [comment]
Merged, closing.
