### ISSUE TITLE
Import PDF galleys using multiple locales

### ISSUE THREAD

**Issue by ewhanson** [mfelczak/bepress#19]
Add the ability to import multi-locale article galleys. This will cover the following cases:

**Article has a single galley with the file name `fulltext.pdf` and no `<galley>` tags**
Import single `fulltext.pdf` and assign it to the current primary locale.

**Article has single`fulltext.pdf` file and a `<galley locale="en_US">` tag**
Import the galley using the locale specified in the `<galley>` tag

**Article has multiple galley files and uses the `<galleys>` tag**
Article galley file names will be appended with locale that corresponds to the locale in the `<galley>` tag.
```xml
<galleys>
    <galley locale="en_US">fulltext.en_US.pdf</galley>
    <galley locale="de_DE">fulltext.de_DE.pdf</galley>
</galleys>
```
The files `fulltext.en_US.pdf` and `fulltext.de_DE.pdf` will be included in the same directory.

**Comment by mfelczak** [comment]
@ewhanson, let's also add the new tags here to the multi-locale sample XML once this has been implemented.

**Comment by ewhanson** [comment]
Hi @mfelczak, I've added support for multi-lingual PDF galleys as described above. I've also included an example in the multi-locale XML sample. Let me know if you have any questions.

Thanks!

PR:
#20

**Comment by mfelczak** [comment]
Merged, closing.
