### ISSUE TITLE
Volume/Issue numbers not picked up correctly

### ISSUE THREAD

**Issue by kaitlinnewson** [mfelczak/bepress#9]
Hi PKP team,

I ran an import from the latest in the stable-3_1_2 branch and am encountering an issue with the volume and issue numbers not being picked up correctly. I have a directory with folders as vol1/iss1, vol2/iss1, etc, but they are all being entered as vol1/iss1. We haven't changed our directory structure since we began using the plugin a couple of years ago. Any ideas what the issue is?

Below is an example of the output, where the second issue should be volume 2. I also confirmed in the UI that all of the issues were entered under vol. 1.

```
Import starting ...====== Vol 1 No 1 (2011) ======

---Article---

'Front Pages' successfully imported

'Consuming Otherness: Loblaws and Specular Consumption' successfully imported

'Balancing the Scales of Legitimacy: The Sulawesi Regional Development Project' successfully imported

'The Church of Elvis' successfully imported

'Baseball. Magic, and Performance' successfully imported

'Nationalism, Ethnicity, and the Cultural Politics of Identity' successfully imported

'Native Education: In the Best Interest of the Children' successfully imported

'Hunter-gatherers and the Ethnographic Analogy: Theoretical Perspectives' successfully imported

'Hunger Pains In a Cold Forest: A Reexamination of the Disappearence of the Beothuk' successfully imported

'Lewis Binford and the New Archaeology' successfully imported

'"Achey-breaky heart:" A Labovian Approach to the Structural Analysis of the Personal Narrative' successfully imported

'Morphological Analysis of the Story, Ne'e Thiyoriwa Ne' Yah Nonwa Onen Teshatahsehs Ne Ohkwari'' successfully imported

'Sex Stereotypes as a Function of Genderlect' successfully imported

'Male Homosexual Speech Patterns in Spontaneous Conversation' successfully imported

'The Development of Hand and Foot in Hominoidea' successfully imported

'Coca Chewing and High Altitude Adaptation' successfully imported

'Neanderthal Speech' successfully imported

'Postcript' successfully imported

====== Vol 1 No 1 (2011) ======

---Article---

'Front Pages' successfully imported

'The Girl Who Cried Wolf /fiction' successfully imported

'Human-like Traits in Early Hominids: Misplaced Analogies in the Interpretation the African Archaeological Record' successfully imported

'Different Worlds: Looking at Jehovah's Witnesses' successfully imported

'HIV: Its Development Within the Human Population' successfully imported

'Sexual Selection in Humans: An Evolutionary and Anthropological Perspective' successfully imported

'Social and Biological Consequences of Nutritional Adaptation: Do the Costs Outweigh the Gains?' successfully imported

'Topic Shift in Casual Conversation' successfully imported

'Advertising Strategies of the Ontario Milk Marketing Board: Milking the Cow for All It's Worth' successfully imported

'Indian Christians: Definition of Identity' successfully imported

'The Neandertal Pelvis with Attention to It's Obstetrical SignifIcance' successfully imported

'TB or not TB: The New World Question' successfully imported

'Syncretism in Two African Cultures' successfully imported

'Carnival: Fighting Oppression with Celebration' successfully imported

'Abura- Dunkwas, Ghana: Impressions of a Secondary School' successfully imported

'Spatial Metaphors as Linguistic Primitives: A Comparison of UP-DOWN Metaphors in Three Languages' successfully imported

'Back Pages' successfully imported

<h1>DB Error: Duplicate entry '980-423' for key 'custom_section_orders_pkey'</h1>ojs2: DB Error: Duplicate entry '980-423' for key 'custom_section_orders_pkey'
```

**Comment by jnugent** [comment]
Hi @kaitlinnewson I just ran this plugin to import three complete journals with hundreds of volumes, dozens of issues per volume, and dozens of articles per issue and we had no problem.  The directory structure should vol#/iss# where everything is entirely numeric.  So, something like 1/1 1/2 1/3 etc.

**Comment by kaitlinnewson** [comment]
Hi @jnugent, I updated our directories to use the 1/1, 2/1, etc, structure, but the issue is still happening. Any other ideas what could be causing this?

Our OJS version is 3.1.2.1 (last upgraded June 13, 2019 - 02:39 PM); PHP 7.1.33.

**Comment by jnugent** [comment]
Hi @kaitlinnewson The only thing that I can think of is that I made a small tweak to the line that generates volume numbers.  If you want to try this, change line 167 or thereabouts back to

https://github.com/mfelczak/bepress/blob/master/BepressImportPlugin.inc.php#L167

and see how it goes.  Failing that, try sprinkling error_log or echo statements around the lines that create the $number or $volume variables, which get passed into the Dom class, which does the heavy lifting.  

If any of these things fix it, I can push up a fix to the branch.  It is strange that I haven't had this problem doing my last import.

Cheers,
Jason

**Comment by kaitlinnewson** [comment]
Thanks @jnugent - changing that line back resolved the issue! Happy to help with any further testing if needed.

**Comment by jnugent** [comment]
Great, glad to hear it!  I'll commit a fix to the stable-3_1_2 branch.
